--累计充值活动配置
local totalRechargeCfg={
    --累计充值
    --needGem:所需金额  单位（元）
    --getGem:返利元宝  单位（元宝）
    --isSpecial:特殊档位 isSpecial=1,特殊档位，普通档位直接显示，特殊档位先隐藏，达到上一档后显示下一档
    [1]={
        ["1"]={
            needGem=6,getGem=60,
        },
        ["2"]={
            needGem=98,getGem=100,
        },
        ["3"]={
            needGem=328,getGem=500,
        },
        ["4"]={
            needGem=648,getGem=800,
        },
        ["5"]={
            needGem=1000,getGem=1000,
        },
        ["6"]={
            needGem=2000,getGem=2000,
        },
        ["7"]={
            isSpecial=1,needGem=4000,getGem=3000,
        },
        ["8"]={
            isSpecial=1,needGem=10000,getGem=7000,
        },
        ["9"]={
            isSpecial=1,needGem=20000,getGem=10000,
        },
    },
    --累计充值
    --needGem:所需金额  单位（元）
    --getGem:返利元宝  单位（元宝）
    --isSpecial:特殊档位 isSpecial=1,特殊档位，普通档位直接显示，特殊档位先隐藏，达到上一档后显示下一档
    [2]={
        ["1"]={
            needGem=6,getGem=60,
        },
        ["2"]={
            needGem=66,getGem=80,
        },
        ["3"]={
            needGem=166,getGem=200,
        },
        ["4"]={
            needGem=366,getGem=500,
        },
        ["5"]={
            needGem=666,getGem=800,
        },
        ["6"]={
            needGem=1000,getGem=1000,
        },
        ["7"]={
            needGem=2000,getGem=2000,
        },
        ["8"]={
            isSpecial=1,needGem=4000,getGem=3000,
        },
        ["9"]={
            isSpecial=1,needGem=10000,getGem=7000,
        },
        ["10"]={
            isSpecial=1,needGem=20000,getGem=10000,
        },
    },
    --累计充值
    --needGem:所需金额  单位（元）
    --getGem:返利元宝  单位（元宝）
    --isSpecial:特殊档位 isSpecial=1,特殊档位，普通档位直接显示，特殊档位先隐藏，达到上一档后显示下一档
    [3]={
        ["1"]={
            needGem=6,getGem=60,
        },
        ["2"]={
            needGem=30,getGem=60,
        },
        ["3"]={
            needGem=98,getGem=100,
        },
        ["4"]={
            needGem=198,getGem=200,
        },
        ["5"]={
            needGem=328,getGem=500,
        },
        ["6"]={
            needGem=648,getGem=800,
        },
        ["7"]={
            needGem=1000,getGem=1000,
        },
        ["8"]={
            needGem=2000,getGem=2000,
        },
        ["9"]={
            isSpecial=1,needGem=4000,getGem=3000,
        },
        ["10"]={
            isSpecial=1,needGem=10000,getGem=7000,
        },
        ["11"]={
            isSpecial=1,needGem=20000,getGem=10000,
        },
    },
    --累计充值
    --needGem:所需金额  单位（元）
    --getGem:返利元宝  单位（元宝）
    --isSpecial:特殊档位 isSpecial=1,特殊档位，普通档位直接显示，特殊档位先隐藏，达到上一档后显示下一档
    [4]={
        ["1"]={
            needGem=6,getGem=60,
        },
        ["2"]={
            needGem=66,getGem=80,
        },
        ["3"]={
            needGem=166,getGem=200,
        },
        ["4"]={
            needGem=366,getGem=500,
        },
        ["5"]={
            needGem=666,getGem=800,
        },
        ["6"]={
            needGem=1000,getGem=1000,
        },
        ["7"]={
            needGem=2000,getGem=2000,
        },
        ["8"]={
            isSpecial=1,needGem=4000,getGem=3000,
        },
        ["9"]={
            isSpecial=1,needGem=10000,getGem=7000,
        },
        ["10"]={
            isSpecial=1,needGem=20000,getGem=10000,
        },
    },
    --累计充值
    --needGem:所需金额  单位（元）
    --getGem:返利元宝  单位（元宝）
    --isSpecial:特殊档位 isSpecial=1,特殊档位，普通档位直接显示，特殊档位先隐藏，达到上一档后显示下一档
    [5]={
        ["1"]={
            needGem=6,getGem=60,
        },
        ["2"]={
            needGem=98,getGem=100,
        },
        ["3"]={
            needGem=328,getGem=500,
        },
        ["4"]={
            needGem=648,getGem=800,
        },
        ["5"]={
            needGem=1000,getGem=1000,
        },
        ["6"]={
            needGem=2000,getGem=2000,
        },
        ["7"]={
            isSpecial=1,needGem=4000,getGem=3000,
        },
        ["8"]={
            isSpecial=1,needGem=10000,getGem=7000,
        },
        ["9"]={
            isSpecial=1,needGem=20000,getGem=10000,
        },
    },
    --累计充值
    --needGem:所需金额  单位（元）
    --getGem:返利元宝  单位（元宝）
    --isSpecial:特殊档位 isSpecial=1,特殊档位，普通档位直接显示，特殊档位先隐藏，达到上一档后显示下一档
    [6]={
        ["1"]={
            needGem=6,getGem=60,
        },
        ["2"]={
            needGem=66,getGem=80,
        },
        ["3"]={
            needGem=166,getGem=200,
        },
        ["4"]={
            needGem=366,getGem=500,
        },
        ["5"]={
            needGem=666,getGem=800,
        },
        ["6"]={
            needGem=1000,getGem=1000,
        },
        ["7"]={
            needGem=2000,getGem=2000,
        },
        ["8"]={
            isSpecial=1,needGem=4000,getGem=3000,
        },
        ["9"]={
            isSpecial=1,needGem=10000,getGem=7000,
        },
        ["10"]={
            isSpecial=1,needGem=20000,getGem=10000,
        },
    },
    --累计充值
    --needGem:所需金额  单位（元）
    --getGem:返利元宝  单位（元宝）
    --isSpecial:特殊档位 isSpecial=1,特殊档位，普通档位直接显示，特殊档位先隐藏，达到上一档后显示下一档
    [7]={
        ["1"]={
            needGem=6,getGem=60,
        },
        ["2"]={
            needGem=66,getGem=80,
        },
        ["3"]={
            needGem=166,getGem=200,
        },
        ["4"]={
            needGem=366,getGem=500,
        },
        ["5"]={
            needGem=666,getGem=800,
        },
        ["6"]={
            needGem=1000,getGem=1000,
        },
        ["7"]={
            needGem=2000,getGem=2000,
        },
        ["8"]={
            isSpecial=1,needGem=4000,getGem=3000,
        },
        ["9"]={
            isSpecial=1,needGem=10000,getGem=7000,
        },
        ["10"]={
            isSpecial=1,needGem=20000,getGem=10000,
        },
    },
    --累计充值
    --needGem:所需金额  单位（元）
    --getGem:返利元宝  单位（元宝）
    --isSpecial:特殊档位 isSpecial=1,特殊档位，普通档位直接显示，特殊档位先隐藏，达到上一档后显示下一档
    [8]={
        ["1"]={
            needGem=6,getGem=60,
        },
        ["2"]={
            needGem=66,getGem=80,
        },
        ["3"]={
            needGem=166,getGem=200,
        },
        ["4"]={
            needGem=366,getGem=500,
        },
        ["5"]={
            needGem=666,getGem=800,
        },
        ["6"]={
            needGem=1000,getGem=1000,
        },
        ["7"]={
            needGem=2000,getGem=2000,
        },
        ["8"]={
            isSpecial=1,needGem=4000,getGem=3000,
        },
        ["9"]={
            isSpecial=1,needGem=10000,getGem=7000,
        },
        ["10"]={
            isSpecial=1,needGem=20000,getGem=10000,
        },
    },
    --累计充值
    --needGem:所需金额  单位（元）
    --getGem:返利元宝  单位（元宝）
    --isSpecial:特殊档位 isSpecial=1,特殊档位，普通档位直接显示，特殊档位先隐藏，达到上一档后显示下一档
    [9]={
        ["1"]={
            needGem=6,getGem=60,
        },
        ["2"]={
            needGem=98,getGem=100,
        },
        ["3"]={
            needGem=328,getGem=500,
        },
        ["4"]={
            needGem=648,getGem=800,
        },
        ["5"]={
            needGem=1000,getGem=1000,
        },
        ["6"]={
            needGem=2000,getGem=2000,
        },
        ["7"]={
            isSpecial=1,needGem=4000,getGem=3000,
        },
        ["8"]={
            isSpecial=1,needGem=10000,getGem=7000,
        },
        ["9"]={
            isSpecial=1,needGem=20000,getGem=10000,
        },
    },
    --累计充值
    --needGem:所需金额  单位（元）
    --getGem:返利元宝  单位（元宝）
    --isSpecial:特殊档位 isSpecial=1,特殊档位，普通档位直接显示，特殊档位先隐藏，达到上一档后显示下一档
    [10]={
        ["1"]={
            needGem=6,getGem=60,
        },
        ["2"]={
            needGem=18,getGem=60,
        },
        ["3"]={
            needGem=68,getGem=80,
        },
        ["4"]={
            needGem=138,getGem=100,
        },
        ["5"]={
            needGem=328,getGem=500,
        },
        ["6"]={
            needGem=648,getGem=800,
        },
        ["7"]={
            needGem=1000,getGem=1000,
        },
        ["8"]={
            needGem=2000,getGem=2000,
        },
        ["9"]={
            isSpecial=1,needGem=4000,getGem=3000,
        },
        ["10"]={
            isSpecial=1,needGem=10000,getGem=7000,
        },
        ["11"]={
            isSpecial=1,needGem=20000,getGem=10000,
        },
    },
    --累计充值
    --needGem:所需金额  单位（元）
    --getGem:返利元宝  单位（元宝）
    --isSpecial:特殊档位 isSpecial=1,特殊档位，普通档位直接显示，特殊档位先隐藏，达到上一档后显示下一档
    [11]={
        ["1"]={
            needGem=6,getGem=60,
        },
        ["2"]={
            needGem=30,getGem=60,
        },
        ["3"]={
            needGem=98,getGem=100,
        },
        ["4"]={
            needGem=198,getGem=200,
        },
        ["5"]={
            needGem=328,getGem=500,
        },
        ["6"]={
            needGem=648,getGem=800,
        },
        ["7"]={
            needGem=1000,getGem=1000,
        },
        ["8"]={
            needGem=2000,getGem=2000,
        },
        ["9"]={
            isSpecial=1,needGem=4000,getGem=3000,
        },
        ["10"]={
            isSpecial=1,needGem=10000,getGem=7000,
        },
        ["11"]={
            isSpecial=1,needGem=20000,getGem=10000,
        },
    },
    --累计充值
    --needGem:所需金额  单位（元）
    --getGem:返利元宝  单位（元宝）
    --isSpecial:特殊档位 isSpecial=1,特殊档位，普通档位直接显示，特殊档位先隐藏，达到上一档后显示下一档
    [12]={
        ["1"]={
            needGem=6,getGem=60,
        },
        ["2"]={
            needGem=18,getGem=60,
        },
        ["3"]={
            needGem=68,getGem=80,
        },
        ["4"]={
            needGem=138,getGem=100,
        },
        ["5"]={
            needGem=328,getGem=500,
        },
        ["6"]={
            needGem=648,getGem=800,
        },
        ["7"]={
            needGem=1000,getGem=1000,
        },
        ["8"]={
            needGem=2000,getGem=2000,
        },
        ["9"]={
            isSpecial=1,needGem=4000,getGem=3000,
        },
        ["10"]={
            isSpecial=1,needGem=10000,getGem=7000,
        },
        ["11"]={
            isSpecial=1,needGem=20000,getGem=10000,
        },
    },
    --累计充值
    --needGem:所需金额  单位（元）
    --getGem:返利元宝  单位（元宝）
    --isSpecial:特殊档位 isSpecial=1,特殊档位，普通档位直接显示，特殊档位先隐藏，达到上一档后显示下一档
    [13]={
        ["1"]={
            needGem=6,getGem=60,
        },
        ["2"]={
            needGem=66,getGem=80,
        },
        ["3"]={
            needGem=166,getGem=200,
        },
        ["4"]={
            needGem=366,getGem=500,
        },
        ["5"]={
            needGem=666,getGem=800,
        },
        ["6"]={
            needGem=1000,getGem=1000,
        },
        ["7"]={
            needGem=2000,getGem=2000,
        },
        ["8"]={
            isSpecial=1,needGem=4000,getGem=3000,
        },
        ["9"]={
            isSpecial=1,needGem=10000,getGem=7000,
        },
        ["10"]={
            isSpecial=1,needGem=20000,getGem=10000,
        },
    },
}
return totalRechargeCfg
