--红颜配置
local wifeCfg={
      --sortId  排序
      --quality  品质
      --dialogue  代入对话的ID
      --wifeSkin  红颜具有的皮肤ID
      --glamour  魅力值  红颜经验 = 魅力值 + 魅力/10 * 魅力/10  向下取整
      --value  寻访进度
      --unlock  解锁条件
      --weight  随机传唤权重
      --ratio1  传唤生孩子几率
      --ratio2  宠幸生孩子几率 
      --servantId  对应门客
      --wifeSkill  红颜技能  att  加成属性  1：武力 2：智力 3：政治 4：魅力  1,2技能加成固定值，3--6技能加成百分比
      --growAtt  每级增加的属性
      --condition  技能解锁，需要红颜亲密度达到 X
    
    ["101"]={       ----冯小怜
        ["sortId"]=1,
        ["quality"]=10,
        ["wifeSkin"]="1011,1012",
        ["glamour"]=40,
        ["value"]=0,
        ["weight"]=10,
        ["ratio1"]=0.7,
        ["ratio2"]=1,
        ["servantId"]="1001",
        ["wifeSkill"]={
            {
                ["att"]={1,2,3,4},
                ["growAtt"]=50,
                ["condition"]=10,
            },
            {
                ["att"]={1,2,3,4},
                ["growAtt"]=100,
                ["condition"]=20,
            },
            {
                ["att"]={1},
                ["growAtt"]=0.005,
                ["condition"]=50,
            },
            {
                ["att"]={2},
                ["growAtt"]=0.005,
                ["condition"]=100,
            },
            {
                ["att"]={3},
                ["growAtt"]=0.005,
                ["condition"]=150,
            },
            {
                ["att"]={4},
                ["growAtt"]=0.005,
                ["condition"]=200,
            },
        },
    },
    ["102"]={       ----花姐
        ["sortId"]=2,
        ["quality"]=10,
        ["wifeSkin"]="1021",
        ["glamour"]=40,
        ["value"]=4,
        ["weight"]=10,
        ["ratio1"]=0.3,
        ["ratio2"]=0.7,
        ["servantId"]="1002",
        ["wifeSkill"]={
            {
                ["att"]={1},
                ["growAtt"]=200,
                ["condition"]=10,
            },
            {
                ["att"]={1},
                ["growAtt"]=400,
                ["condition"]=20,
            },
            {
                ["att"]={2},
                ["growAtt"]=0.005,
                ["condition"]=50,
            },
            {
                ["att"]={3},
                ["growAtt"]=0.005,
                ["condition"]=100,
            },
            {
                ["att"]={4},
                ["growAtt"]=0.005,
                ["condition"]=150,
            },
            {
                ["att"]={1},
                ["growAtt"]=0.005,
                ["condition"]=200,
            },
        },
    },
    ["103"]={       ----和硕格格
        ["sortId"]=3,
        ["quality"]=10,
        ["wifeSkin"]="1031",
        ["glamour"]=40,
        ["value"]=4,
        ["weight"]=10,
        ["ratio1"]=0.3,
        ["ratio2"]=0.7,
        ["servantId"]="1003",
        ["wifeSkill"]={
            {
                ["att"]={2},
                ["growAtt"]=200,
                ["condition"]=10,
            },
            {
                ["att"]={2},
                ["growAtt"]=400,
                ["condition"]=20,
            },
            {
                ["att"]={1},
                ["growAtt"]=0.005,
                ["condition"]=50,
            },
            {
                ["att"]={3},
                ["growAtt"]=0.005,
                ["condition"]=100,
            },
            {
                ["att"]={4},
                ["growAtt"]=0.005,
                ["condition"]=150,
            },
            {
                ["att"]={2},
                ["growAtt"]=0.005,
                ["condition"]=200,
            },
        },
    },
    ["104"]={       ----小翠
        ["sortId"]=4,
        ["quality"]=10,
        ["glamour"]=40,
        ["value"]=4,
        ["weight"]=10,
        ["ratio1"]=0.3,
        ["ratio2"]=0.7,
        ["servantId"]="1004",
        ["wifeSkill"]={
            {
                ["att"]={3},
                ["growAtt"]=200,
                ["condition"]=10,
            },
            {
                ["att"]={3},
                ["growAtt"]=400,
                ["condition"]=20,
            },
            {
                ["att"]={1},
                ["growAtt"]=0.005,
                ["condition"]=50,
            },
            {
                ["att"]={2},
                ["growAtt"]=0.005,
                ["condition"]=100,
            },
            {
                ["att"]={4},
                ["growAtt"]=0.005,
                ["condition"]=150,
            },
            {
                ["att"]={3},
                ["growAtt"]=0.005,
                ["condition"]=200,
            },
        },
    },
    ["105"]={       ----林黛玉
        ["sortId"]=5,
        ["quality"]=10,
        ["glamour"]=40,
        ["value"]=4,
        ["weight"]=10,
        ["ratio1"]=0.3,
        ["ratio2"]=0.7,
        ["servantId"]="1005",
        ["wifeSkill"]={
            {
                ["att"]={4},
                ["growAtt"]=200,
                ["condition"]=10,
            },
            {
                ["att"]={4},
                ["growAtt"]=400,
                ["condition"]=20,
            },
            {
                ["att"]={1},
                ["growAtt"]=0.005,
                ["condition"]=50,
            },
            {
                ["att"]={2},
                ["growAtt"]=0.005,
                ["condition"]=100,
            },
            {
                ["att"]={3},
                ["growAtt"]=0.005,
                ["condition"]=150,
            },
            {
                ["att"]={4},
                ["growAtt"]=0.005,
                ["condition"]=200,
            },
        },
    },
    ["106"]={       ----年妃
        ["sortId"]=6,
        ["quality"]=10,
        ["glamour"]=50,
        ["value"]=5,
        ["weight"]=10,
        ["ratio1"]=0.3,
        ["ratio2"]=0.7,
        ["servantId"]="1006",
        ["wifeSkill"]={
            {
                ["att"]={1},
                ["growAtt"]=200,
                ["condition"]=10,
            },
            {
                ["att"]={1},
                ["growAtt"]=400,
                ["condition"]=20,
            },
            {
                ["att"]={2},
                ["growAtt"]=0.005,
                ["condition"]=50,
            },
            {
                ["att"]={3},
                ["growAtt"]=0.005,
                ["condition"]=100,
            },
            {
                ["att"]={4},
                ["growAtt"]=0.005,
                ["condition"]=150,
            },
            {
                ["att"]={1},
                ["growAtt"]=0.005,
                ["condition"]=200,
            },
        },
    },
    ["107"]={       ----双儿
        ["sortId"]=7,
        ["quality"]=10,
        ["glamour"]=50,
        ["value"]=6,
        ["weight"]=10,
        ["ratio1"]=0.3,
        ["ratio2"]=0.7,
        ["servantId"]="1007",
        ["wifeSkill"]={
            {
                ["att"]={2},
                ["growAtt"]=200,
                ["condition"]=10,
            },
            {
                ["att"]={2},
                ["growAtt"]=400,
                ["condition"]=20,
            },
            {
                ["att"]={1},
                ["growAtt"]=0.005,
                ["condition"]=50,
            },
            {
                ["att"]={3},
                ["growAtt"]=0.005,
                ["condition"]=100,
            },
            {
                ["att"]={4},
                ["growAtt"]=0.005,
                ["condition"]=150,
            },
            {
                ["att"]={2},
                ["growAtt"]=0.005,
                ["condition"]=200,
            },
        },
    },
    ["108"]={       ----陈圆圆
        ["sortId"]=8,
        ["quality"]=10,
        ["glamour"]=50,
        ["value"]=7,
        ["weight"]=10,
        ["ratio1"]=0.3,
        ["ratio2"]=0.7,
        ["servantId"]="1008",
        ["wifeSkill"]={
            {
                ["att"]={3},
                ["growAtt"]=200,
                ["condition"]=10,
            },
            {
                ["att"]={3},
                ["growAtt"]=400,
                ["condition"]=20,
            },
            {
                ["att"]={1},
                ["growAtt"]=0.005,
                ["condition"]=50,
            },
            {
                ["att"]={2},
                ["growAtt"]=0.005,
                ["condition"]=100,
            },
            {
                ["att"]={4},
                ["growAtt"]=0.005,
                ["condition"]=150,
            },
            {
                ["att"]={3},
                ["growAtt"]=0.005,
                ["condition"]=200,
            },
        },
    },
    ["109"]={       ----颜如玉
        ["sortId"]=9,
        ["quality"]=10,
        ["glamour"]=50,
        ["value"]=8,
        ["weight"]=10,
        ["ratio1"]=0.3,
        ["ratio2"]=0.7,
        ["servantId"]="1009",
        ["wifeSkill"]={
            {
                ["att"]={4},
                ["growAtt"]=200,
                ["condition"]=10,
            },
            {
                ["att"]={4},
                ["growAtt"]=400,
                ["condition"]=20,
            },
            {
                ["att"]={1},
                ["growAtt"]=0.005,
                ["condition"]=50,
            },
            {
                ["att"]={2},
                ["growAtt"]=0.005,
                ["condition"]=100,
            },
            {
                ["att"]={3},
                ["growAtt"]=0.005,
                ["condition"]=150,
            },
            {
                ["att"]={4},
                ["growAtt"]=0.005,
                ["condition"]=200,
            },
        },
    },
    ["201"]={       ----董小宛
        ["sortId"]=10,
        ["quality"]=10,
        ["glamour"]=60,
        ["value"]=10,
        ["weight"]=10,
        ["ratio1"]=0.3,
        ["ratio2"]=0.7,
        ["servantId"]="1023",
        ["wifeSkill"]={
            {
                ["att"]={1},
                ["growAtt"]=200,
                ["condition"]=10,
            },
            {
                ["att"]={1},
                ["growAtt"]=400,
                ["condition"]=20,
            },
            {
                ["att"]={3},
                ["growAtt"]=0.005,
                ["condition"]=50,
            },
            {
                ["att"]={4},
                ["growAtt"]=0.005,
                ["condition"]=100,
            },
            {
                ["att"]={2},
                ["growAtt"]=0.005,
                ["condition"]=150,
            },
            {
                ["att"]={1},
                ["growAtt"]=0.005,
                ["condition"]=200,
            },
        },
    },
    ["202"]={       ----柳如是
        ["sortId"]=11,
        ["quality"]=10,
        ["wifeSkin"]="2021",
        ["glamour"]=60,
        ["value"]=12,
        ["weight"]=10,
        ["ratio1"]=0.3,
        ["ratio2"]=0.7,
        ["servantId"]="1024",
        ["wifeSkill"]={
            {
                ["att"]={1},
                ["growAtt"]=200,
                ["condition"]=10,
            },
            {
                ["att"]={1},
                ["growAtt"]=400,
                ["condition"]=20,
            },
            {
                ["att"]={2},
                ["growAtt"]=0.005,
                ["condition"]=50,
            },
            {
                ["att"]={4},
                ["growAtt"]=0.005,
                ["condition"]=100,
            },
            {
                ["att"]={3},
                ["growAtt"]=0.005,
                ["condition"]=150,
            },
            {
                ["att"]={1},
                ["growAtt"]=0.005,
                ["condition"]=200,
            },
        },
    },
    ["203"]={       ----薛宝钗
        ["sortId"]=12,
        ["quality"]=10,
        ["glamour"]=60,
        ["value"]=14,
        ["weight"]=10,
        ["ratio1"]=0.3,
        ["ratio2"]=0.7,
        ["servantId"]="1025",
        ["wifeSkill"]={
            {
                ["att"]={3},
                ["growAtt"]=200,
                ["condition"]=10,
            },
            {
                ["att"]={3},
                ["growAtt"]=400,
                ["condition"]=20,
            },
            {
                ["att"]={4},
                ["growAtt"]=0.005,
                ["condition"]=50,
            },
            {
                ["att"]={1},
                ["growAtt"]=0.005,
                ["condition"]=100,
            },
            {
                ["att"]={2},
                ["growAtt"]=0.005,
                ["condition"]=150,
            },
            {
                ["att"]={3},
                ["growAtt"]=0.005,
                ["condition"]=200,
            },
        },
    },
    ["204"]={       ----李师师
        ["sortId"]=13,
        ["quality"]=10,
        ["glamour"]=60,
        ["value"]=16,
        ["weight"]=10,
        ["ratio1"]=0.3,
        ["ratio2"]=0.7,
        ["servantId"]="1026",
        ["wifeSkill"]={
            {
                ["att"]={2},
                ["growAtt"]=200,
                ["condition"]=10,
            },
            {
                ["att"]={2},
                ["growAtt"]=400,
                ["condition"]=20,
            },
            {
                ["att"]={1},
                ["growAtt"]=0.005,
                ["condition"]=50,
            },
            {
                ["att"]={3},
                ["growAtt"]=0.005,
                ["condition"]=100,
            },
            {
                ["att"]={4},
                ["growAtt"]=0.005,
                ["condition"]=150,
            },
            {
                ["att"]={2},
                ["growAtt"]=0.005,
                ["condition"]=200,
            },
        },
    },
    ["205"]={       ----罗姗娜
        ["sortId"]=14,
        ["quality"]=10,
        ["glamour"]=60,
        ["value"]=18,
        ["weight"]=10,
        ["ratio1"]=0.3,
        ["ratio2"]=0.7,
        ["servantId"]="1027",
        ["wifeSkill"]={
            {
                ["att"]={4},
                ["growAtt"]=200,
                ["condition"]=10,
            },
            {
                ["att"]={4},
                ["growAtt"]=400,
                ["condition"]=20,
            },
            {
                ["att"]={1},
                ["growAtt"]=0.005,
                ["condition"]=50,
            },
            {
                ["att"]={2},
                ["growAtt"]=0.005,
                ["condition"]=100,
            },
            {
                ["att"]={3},
                ["growAtt"]=0.005,
                ["condition"]=150,
            },
            {
                ["att"]={4},
                ["growAtt"]=0.005,
                ["condition"]=200,
            },
        },
    },
    ["206"]={       ----郭瓖
        ["sortId"]=15,
        ["quality"]=10,
        ["glamour"]=60,
        ["value"]=20,
        ["weight"]=10,
        ["ratio1"]=0.3,
        ["ratio2"]=0.7,
        ["servantId"]="1028",
        ["wifeSkill"]={
            {
                ["att"]={1},
                ["growAtt"]=200,
                ["condition"]=10,
            },
            {
                ["att"]={1},
                ["growAtt"]=400,
                ["condition"]=20,
            },
            {
                ["att"]={3},
                ["growAtt"]=0.005,
                ["condition"]=50,
            },
            {
                ["att"]={2},
                ["growAtt"]=0.005,
                ["condition"]=100,
            },
            {
                ["att"]={4},
                ["growAtt"]=0.005,
                ["condition"]=150,
            },
            {
                ["att"]={1},
                ["growAtt"]=0.005,
                ["condition"]=200,
            },
        },
    },
    ["207"]={       ----长平公主
        ["sortId"]=16,
        ["quality"]=10,
        ["wifeSkin"]="2071",
        ["glamour"]=60,
        ["unlock"]={["needPower"]=50000},
        ["weight"]=10,
        ["ratio1"]=0.27,
        ["ratio2"]=0.72,
        ["servantId"]="1029",
        ["wifeSkill"]={
            {
                ["att"]={1},
                ["growAtt"]=200,
                ["condition"]=10,
            },
            {
                ["att"]={1},
                ["growAtt"]=400,
                ["condition"]=20,
            },
            {
                ["att"]={3},
                ["growAtt"]=0.005,
                ["condition"]=50,
            },
            {
                ["att"]={2},
                ["growAtt"]=0.005,
                ["condition"]=100,
            },
            {
                ["att"]={4},
                ["growAtt"]=0.005,
                ["condition"]=150,
            },
            {
                ["att"]={1},
                ["growAtt"]=0.005,
                ["condition"]=200,
            },
        },
    },
    ["208"]={       ----金镶玉
        ["sortId"]=17,
        ["quality"]=10,
        ["glamour"]=70,
        ["unlock"]={["needPower"]=200000},
        ["weight"]=10,
        ["ratio1"]=0.24,
        ["ratio2"]=0.74,
        ["servantId"]="1030",
        ["wifeSkill"]={
            {
                ["att"]={2},
                ["growAtt"]=200,
                ["condition"]=10,
            },
            {
                ["att"]={2},
                ["growAtt"]=400,
                ["condition"]=20,
            },
            {
                ["att"]={1},
                ["growAtt"]=0.005,
                ["condition"]=50,
            },
            {
                ["att"]={3},
                ["growAtt"]=0.005,
                ["condition"]=100,
            },
            {
                ["att"]={4},
                ["growAtt"]=0.005,
                ["condition"]=150,
            },
            {
                ["att"]={2},
                ["growAtt"]=0.005,
                ["condition"]=200,
            },
        },
    },
    ["209"]={       ----阿市
        ["sortId"]=18,
        ["quality"]=10,
        ["glamour"]=80,
        ["unlock"]={["needPower"]=500000},
        ["weight"]=10,
        ["ratio1"]=0.21,
        ["ratio2"]=0.76,
        ["servantId"]="1031",
        ["wifeSkill"]={
            {
                ["att"]={3},
                ["growAtt"]=200,
                ["condition"]=10,
            },
            {
                ["att"]={3},
                ["growAtt"]=400,
                ["condition"]=20,
            },
            {
                ["att"]={1},
                ["growAtt"]=0.005,
                ["condition"]=50,
            },
            {
                ["att"]={2},
                ["growAtt"]=0.005,
                ["condition"]=100,
            },
            {
                ["att"]={4},
                ["growAtt"]=0.005,
                ["condition"]=150,
            },
            {
                ["att"]={3},
                ["growAtt"]=0.005,
                ["condition"]=200,
            },
        },
    },
    ["210"]={       ----甄宓
        ["sortId"]=19,
        ["quality"]=10,
        ["glamour"]=90,
        ["unlock"]={["needPower"]=1000000},
        ["weight"]=10,
        ["ratio1"]=0.2,
        ["ratio2"]=0.78,
        ["servantId"]="1032",
        ["wifeSkill"]={
            {
                ["att"]={4},
                ["growAtt"]=200,
                ["condition"]=10,
            },
            {
                ["att"]={4},
                ["growAtt"]=400,
                ["condition"]=20,
            },
            {
                ["att"]={1},
                ["growAtt"]=0.005,
                ["condition"]=50,
            },
            {
                ["att"]={2},
                ["growAtt"]=0.005,
                ["condition"]=100,
            },
            {
                ["att"]={3},
                ["growAtt"]=0.005,
                ["condition"]=150,
            },
            {
                ["att"]={4},
                ["growAtt"]=0.005,
                ["condition"]=200,
            },
        },
    },
    ["211"]={       ----安希郡主
        ["sortId"]=27,
        ["quality"]=10,
        ["glamour"]=60,
        ["value"]=20,
        ["weight"]=10,
        ["ratio1"]=0.3,
        ["ratio2"]=0.7,
        ["servantId"]="1010",
        ["wifeSkill"]={
            {
                ["att"]={1},
                ["growAtt"]=200,
                ["condition"]=10,
            },
            {
                ["att"]={1},
                ["growAtt"]=400,
                ["condition"]=20,
            },
            {
                ["att"]={2},
                ["growAtt"]=0.005,
                ["condition"]=50,
            },
            {
                ["att"]={3},
                ["growAtt"]=0.005,
                ["condition"]=100,
            },
            {
                ["att"]={4},
                ["growAtt"]=0.005,
                ["condition"]=150,
            },
            {
                ["att"]={1},
                ["growAtt"]=0.005,
                ["condition"]=200,
            },
        },
    },
    ["212"]={       ----媞妹
        ["sortId"]=28,
        ["quality"]=10,
        ["glamour"]=60,
        ["value"]=20,
        ["weight"]=10,
        ["ratio1"]=0.3,
        ["ratio2"]=0.7,
        ["servantId"]="1011",
        ["wifeSkill"]={
            {
                ["att"]={2},
                ["growAtt"]=200,
                ["condition"]=10,
            },
            {
                ["att"]={2},
                ["growAtt"]=400,
                ["condition"]=20,
            },
            {
                ["att"]={1},
                ["growAtt"]=0.005,
                ["condition"]=50,
            },
            {
                ["att"]={3},
                ["growAtt"]=0.005,
                ["condition"]=100,
            },
            {
                ["att"]={4},
                ["growAtt"]=0.005,
                ["condition"]=150,
            },
            {
                ["att"]={2},
                ["growAtt"]=0.005,
                ["condition"]=200,
            },
        },
    },
    ["213"]={       ----米莎公主
        ["sortId"]=30,
        ["quality"]=10,
        ["glamour"]=200,
        ["unlock"]={["needActive"]=1},
        ["weight"]=10,
        ["ratio1"]=0.3,
        ["ratio2"]=0.7,
        ["servantId"]="1014",
        ["wifeSkill"]={
            {
                ["att"]={1},
                ["growAtt"]=200,
                ["condition"]=10,
            },
            {
                ["att"]={1},
                ["growAtt"]=400,
                ["condition"]=20,
            },
            {
                ["att"]={2},
                ["growAtt"]=0.005,
                ["condition"]=50,
            },
            {
                ["att"]={3},
                ["growAtt"]=0.005,
                ["condition"]=100,
            },
            {
                ["att"]={4},
                ["growAtt"]=0.005,
                ["condition"]=150,
            },
            {
                ["att"]={1},
                ["growAtt"]=0.005,
                ["condition"]=200,
            },
        },
    },
    ["214"]={       ----田芯匠
        ["sortId"]=31,
        ["quality"]=10,
        ["glamour"]=100,
        ["unlock"]={["needActive"]=2},
        ["weight"]=10,
        ["ratio1"]=0.3,
        ["ratio2"]=0.7,
        ["servantId"]="1012",
        ["wifeSkill"]={
            {
                ["att"]={3},
                ["growAtt"]=200,
                ["condition"]=10,
            },
            {
                ["att"]={3},
                ["growAtt"]=400,
                ["condition"]=20,
            },
            {
                ["att"]={1},
                ["growAtt"]=0.005,
                ["condition"]=50,
            },
            {
                ["att"]={2},
                ["growAtt"]=0.005,
                ["condition"]=100,
            },
            {
                ["att"]={4},
                ["growAtt"]=0.005,
                ["condition"]=150,
            },
            {
                ["att"]={3},
                ["growAtt"]=0.005,
                ["condition"]=200,
            },
        },
    },
    ["215"]={       ----鱼玄机
        ["sortId"]=32,
        ["quality"]=10,
        ["glamour"]=60,
        ["value"]=30,
        ["weight"]=10,
        ["ratio1"]=0.3,
        ["ratio2"]=0.7,
        ["servantId"]="1013",
        ["wifeSkill"]={
            {
                ["att"]={4},
                ["growAtt"]=200,
                ["condition"]=10,
            },
            {
                ["att"]={4},
                ["growAtt"]=400,
                ["condition"]=20,
            },
            {
                ["att"]={1},
                ["growAtt"]=0.005,
                ["condition"]=50,
            },
            {
                ["att"]={2},
                ["growAtt"]=0.005,
                ["condition"]=100,
            },
            {
                ["att"]={3},
                ["growAtt"]=0.005,
                ["condition"]=150,
            },
            {
                ["att"]={4},
                ["growAtt"]=0.005,
                ["condition"]=200,
            },
        },
    },
    ["303"]={       ----西施
        ["sortId"]=20,
        ["quality"]=10,
        ["wifeSkin"]="3031",
        ["glamour"]=100,
        ["unlock"]={["needVip"]=2},
        ["weight"]=10,
        ["ratio1"]=0.2,
        ["ratio2"]=0.83,
        ["servantId"]="1034",
        ["wifeSkill"]={
            {
                ["att"]={1},
                ["growAtt"]=200,
                ["condition"]=10,
            },
            {
                ["att"]={1},
                ["growAtt"]=400,
                ["condition"]=20,
            },
            {
                ["att"]={2},
                ["growAtt"]=0.005,
                ["condition"]=50,
            },
            {
                ["att"]={3},
                ["growAtt"]=0.005,
                ["condition"]=100,
            },
            {
                ["att"]={4},
                ["growAtt"]=0.005,
                ["condition"]=150,
            },
            {
                ["att"]={1},
                ["growAtt"]=0.005,
                ["condition"]=200,
            },
        },
    },
    ["302"]={       ----貂蝉
        ["sortId"]=21,
        ["quality"]=10,
        ["wifeSkin"]="3021",
        ["glamour"]=200,
        ["unlock"]={["needVip"]=4},
        ["weight"]=10,
        ["ratio1"]=0.2,
        ["ratio2"]=0.8,
        ["servantId"]="1033",
        ["wifeSkill"]={
            {
                ["att"]={1},
                ["growAtt"]=200,
                ["condition"]=10,
            },
            {
                ["att"]={1},
                ["growAtt"]=400,
                ["condition"]=20,
            },
            {
                ["att"]={3},
                ["growAtt"]=0.005,
                ["condition"]=50,
            },
            {
                ["att"]={2},
                ["growAtt"]=0.005,
                ["condition"]=100,
            },
            {
                ["att"]={4},
                ["growAtt"]=0.005,
                ["condition"]=150,
            },
            {
                ["att"]={1},
                ["growAtt"]=0.005,
                ["condition"]=200,
            },
        },
    },
    ["304"]={       ----杨玉环
        ["sortId"]=22,
        ["quality"]=10,
        ["wifeSkin"]="3041",
        ["glamour"]=500,
        ["unlock"]={["needVip"]=6},
        ["weight"]=10,
        ["ratio1"]=0.2,
        ["ratio2"]=0.87,
        ["servantId"]="1036",
        ["wifeSkill"]={
            {
                ["att"]={1,2},
                ["growAtt"]=100,
                ["condition"]=10,
            },
            {
                ["att"]={1,2},
                ["growAtt"]=200,
                ["condition"]=20,
            },
            {
                ["att"]={3},
                ["growAtt"]=0.005,
                ["condition"]=50,
            },
            {
                ["att"]={4},
                ["growAtt"]=0.005,
                ["condition"]=100,
            },
            {
                ["att"]={2},
                ["growAtt"]=0.005,
                ["condition"]=150,
            },
            {
                ["att"]={1},
                ["growAtt"]=0.005,
                ["condition"]=200,
            },
        },
    },
    ["305"]={       ----王昭君
        ["sortId"]=23,
        ["quality"]=10,
        ["wifeSkin"]="3051",
        ["glamour"]=1000,
        ["unlock"]={["needVip"]=8},
        ["weight"]=10,
        ["ratio1"]=0.2,
        ["ratio2"]=0.9,
        ["servantId"]="1035",
        ["wifeSkill"]={
            {
                ["att"]={1,4},
                ["growAtt"]=100,
                ["condition"]=10,
            },
            {
                ["att"]={1,4},
                ["growAtt"]=200,
                ["condition"]=20,
            },
            {
                ["att"]={3},
                ["growAtt"]=0.005,
                ["condition"]=50,
            },
            {
                ["att"]={2},
                ["growAtt"]=0.005,
                ["condition"]=100,
            },
            {
                ["att"]={4},
                ["growAtt"]=0.005,
                ["condition"]=150,
            },
            {
                ["att"]={1},
                ["growAtt"]=0.005,
                ["condition"]=200,
            },
        },
    },
    ["306"]={       ----小乔
        ["sortId"]=24,
        ["quality"]=10,
        ["glamour"]=2000,
        ["unlock"]={["needVip"]=9},
        ["weight"]=10,
        ["ratio1"]=0.2,
        ["ratio2"]=0.9,
        ["servantId"]="1037",
        ["wifeSkill"]={
            {
                ["att"]={1},
                ["growAtt"]=200,
                ["condition"]=10,
            },
            {
                ["att"]={1},
                ["growAtt"]=400,
                ["condition"]=20,
            },
            {
                ["att"]={2},
                ["growAtt"]=0.005,
                ["condition"]=50,
            },
            {
                ["att"]={3},
                ["growAtt"]=0.005,
                ["condition"]=100,
            },
            {
                ["att"]={4},
                ["growAtt"]=0.005,
                ["condition"]=150,
            },
            {
                ["att"]={1},
                ["growAtt"]=0.005,
                ["condition"]=200,
            },
        },
    },
    ["307"]={       ----大乔
        ["sortId"]=25,
        ["quality"]=10,
        ["glamour"]=4000,
        ["unlock"]={["needVip"]=10},
        ["weight"]=10,
        ["ratio1"]=0.2,
        ["ratio2"]=0.87,
        ["servantId"]="1038",
        ["wifeSkill"]={
            {
                ["att"]={1},
                ["growAtt"]=200,
                ["condition"]=10,
            },
            {
                ["att"]={1},
                ["growAtt"]=400,
                ["condition"]=20,
            },
            {
                ["att"]={2},
                ["growAtt"]=0.005,
                ["condition"]=50,
            },
            {
                ["att"]={3},
                ["growAtt"]=0.005,
                ["condition"]=100,
            },
            {
                ["att"]={4},
                ["growAtt"]=0.005,
                ["condition"]=150,
            },
            {
                ["att"]={1},
                ["growAtt"]=0.005,
                ["condition"]=200,
            },
        },
    },
    ["308"]={       ----武则天
        ["sortId"]=29,
        ["quality"]=10,
        ["glamour"]=6000,
        ["unlock"]={["needVip"]=11},
        ["weight"]=10,
        ["ratio1"]=0.2,
        ["ratio2"]=0.9,
        ["servantId"]="1039",
        ["wifeSkill"]={
            {
                ["att"]={1,2},
                ["growAtt"]=100,
                ["condition"]=10,
            },
            {
                ["att"]={1,2},
                ["growAtt"]=200,
                ["condition"]=20,
            },
            {
                ["att"]={3},
                ["growAtt"]=0.005,
                ["condition"]=50,
            },
            {
                ["att"]={4},
                ["growAtt"]=0.005,
                ["condition"]=100,
            },
            {
                ["att"]={2},
                ["growAtt"]=0.005,
                ["condition"]=150,
            },
            {
                ["att"]={1},
                ["growAtt"]=0.005,
                ["condition"]=200,
            },
        },
    },
    ["310"]={       ----上官婉儿
        ["sortId"]=26,
        ["quality"]=10,
        ["wifeSkin"]="3101",
        ["glamour"]=100,
        ["unlock"]={["needQQ"]=1},
        ["weight"]=10,
        ["ratio1"]=0.3,
        ["ratio2"]=0.7,
        ["servantId"]="1050",
        ["wifeSkill"]={
            {
                ["att"]={2,3},
                ["growAtt"]=100,
                ["condition"]=10,
            },
            {
                ["att"]={2,3},
                ["growAtt"]=200,
                ["condition"]=20,
            },
            {
                ["att"]={1},
                ["growAtt"]=0.005,
                ["condition"]=50,
            },
            {
                ["att"]={4},
                ["growAtt"]=0.005,
                ["condition"]=100,
            },
            {
                ["att"]={3},
                ["growAtt"]=0.005,
                ["condition"]=150,
            },
            {
                ["att"]={2},
                ["growAtt"]=0.005,
                ["condition"]=200,
            },
        },
    },
}
return wifeCfg
